spring:
  h2:
    console:
      enabled: false
      settings:
        web-allow-others: false
  
  security:
    user:
      name: ${ADMIN_USERNAME} 
      password: ${ADMIN_PASSWORD} 
      roles: ADMIN

server:
  error:
    include-stacktrace: never
    include-message: always
    whitelabel:
      enabled: true  
  
  headers:
    content-security-policy: "default-src 'self'"
    x-content-type-options: nosniff
    x-frame-options: DENY
    x-xss-protection: "0"

logging:
  level:
    org.springframework.security: WARN
  file:
    name: logs/app.log
    max-size: 10MB
    max-history: 30